// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use actual Supabase project configuration
const SUPABASE_URL = 'https://kbwyocwpyxncnwmywama.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtid3lvY3dweXhuY253bXl3YW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjU2NTYsImV4cCI6MjA3MDY0MTY1Nn0.9FlyNu6YTCkTK_aCgnAcGqYM-SgsRpvKfqb0CrdYt7M';

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";